### ISSUE TITLE
Mysqldump no external host possible

### ISSUE THREAD

**Issue by janz93** [hanami/model#409]
I have the following docker-compose setup

> docker-compose.yml

```
version: "3.1"
services:
  database:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=deu_news_2011_10K
      - MYSQL_USER=foo
      - MYSQL_PASSWORD=bar

  web:
    build: ./web
    command: bundle exec hanami server --host 0.0.0.0
    volumes:
      - ./web:/app
    ports:
      - "2300:2300"
    depends_on:
      - database
    environment:
      - DATABASE_URL=mysql2://foo:bar@database/deu_news_2011_10K
```

> enviroment.rb
```
require 'bundler/setup'
require 'hanami/setup'
require 'hanami/model'
require_relative '../lib/bookshelf'
require_relative '../apps/web/application'

Hanami.configure do
  mount Web::Application, at: '/'

  model do
    ##
    # Database adapter
    #
    # Available options:
    #
    #  * SQL adapter
    #    adapter :sql, 'sqlite://db/bookshelf_development.sqlite3'
    #    adapter :sql, 'postgresql://localhost/bookshelf_development'
    #    adapter :sql, 'mysql://localhost/bookshelf_development'
    #
    adapter :sql, ENV['DATABASE_URL']

    ##
    # Migrations
    #
    migrations 'db/migrations'
    schema     'db/schema.sql'
  end

  mailer do
    root 'lib/bookshelf/mailers'

    # See http://hanamirb.org/guides/mailers/delivery
    delivery :test
  end

  environment :development do
    # See: http://hanamirb.org/guides/projects/logging
    logger level: :debug
  end

  environment :production do
    logger level: :info, formatter: :json

    mailer do
      delivery :smtp, address: ENV['SMTP_HOST'], port: ENV['SMTP_PORT']
    end
  end
end
```

during the `docker-compose run web bundle exec hanami db apply`
I get the following error message
`mysqldump: Got error: 2002: "Can't connect to local MySQL server through socket '/run/mysqld/mysqld.sock' (2 "No such file or directory")" when trying to connect`

this is because the [mysql adapter](https://github.com/hanami/model/blob/master/lib/hanami/model/migrator/mysql_adapter.rb#L79) assumes the command will run in a localhost connection environment

instead I would purpose something similar as this
`system "mysqldump --host=#{host} --password=#{password} --user=#{username} --no-data --skip-comments  --ignore-table=#{database}.#{migrations_table} #{database} > #{schema}"`
